### PR TITLE
Add the weekday and ICS for weekly meetings

### PR DESCRIPTION
**Pull request by YorikSar**
It would make it easier to add it to your calendar. Set start date in .ics to Jul 14.

### CODE REVIEW

**Comment by infinisil** [comment]
I don't think it's a good idea to have a static weekly repeating `.ics` file because it will get outdated eventually as the meeting is cancelled/moved/changed/etc, which could lead to confusion.

I created a google calendar event in the [NixOS google calendar](https://calendar.google.com/calendar/embed?src=b9o52fobqjak8oq8lfkhg3t0qg%40group.calendar.google.com&ctz=Europe%2FZurich) in the hopes of it having some nice `.ics` auto-updating magic, but no such thing exists (`.ics` are very static).

However, what does work is that it's very easy to invite people to that event with Google Calendar and collect RSVP's and send automated updates to the people in the meeting. I think that's the best thing for people who regularly want to participate. It's even possible for anybody being invited to the meeting to invite more people.

**Comment by infinisil** [comment]
@YorikSar I'm now referring and linking to the Google Calendar event with https://github.com/nixpkgs-architecture/.github/commit/9bf14df2b2b80aa30b0f24b26ece68f0c086f993, also recommending people to get invited to the meeting for automated updates. Does that sound good to you?

**Comment by infinisil** [comment]
I also changed the meeting to be on Wednesday instead, there's the Nix documentation team around the same time on Thursday

**Comment by YorikSar** [comment]
Sure, we can use Google Calendar as a source of truth for this. I thought local .ics file can be also helpful in case people have issues with Google Calendar one. By the way, I think you should be able to subscribe to GitHub URL for .ics in you Calendar.

I'm totally fine with keeping only Google Calendar. By the way, as far as I remember, it updates its iCal feeds daily, so it's not static, it just isn't changing often.

**Comment by YorikSar** [comment]
Maybe we shouldn't refer to a specific time in the text, and just link to the calendar event?

**Comment by infinisil** [comment]
It's at least somewhat manageable to update the timeslot in this single location, but yeah maybe it should be removed if it's very variable

**Pull request closed without merging**
